### PR TITLE
Ws shinken

### LINKED ISSUE #2: WS-Shinken support

### PR DESCRIPTION
**Pull request by michel-cf**
Fixes #2 

- Wrong headers where used, resulting in failure to parse arguments
- Result code was not passed to ws_shinken output

### CODE REVIEW

**Comment by GMLudo** [comment]
Do you test with shinken ?
They changed the payload format ?

**Comment by michel-cf** [comment]
Yes, I have tested it:

My Shinken server gets the data in nicely

image
image
image
image

**Comment by michel-cf** [comment]
I compared the calls to those on this page: https://github.com/shinken-monitoring/mod-ws-arbiter

**Comment by ludovic-gasc** [comment]
Ok, thank you.

**Pull request merged**
